//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobsWithDescription
    {
        public int Rank { get; set; }
        public string Code { get; set; }
        public Nullable<double> Probability { get; set; }
        public string Occupation { get; set; }
        public string Description { get; set; }
    }
}
