//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group
{
    using System;
    using System.Collections.Generic;
    
    public partial class relatedOccupation
    {
        public string Occupation { get; set; }
        public string RelatedOccupation1 { get; set; }
        public string RelatedCode { get; set; }
        public int ID { get; set; }
    }
}
